import type { CSSProperties } from "react";
import {
  Accessibility,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Badge,
  BadgeCheck,
  BadgeIndianRupee,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  BusFront,
  CalendarDays,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleCheckBig,
  CircleEllipsis,
  CircleQuestionMark,
  Clock,
  Cloudy,
  Download,
  Droplet,
  Factory,
  FileText,
  Footprints,
  Gavel,
  Globe,
  Home,
  Info,
  Landmark,
  Leaf,
  ListChecks,
  ListFilter,
  LocateFixed,
  Map,
  MapPin,
  MapPinPlus,
  MapPinned,
  MousePointerClick,
  Network,
  NotebookPen,
  PawPrint,
  Plus,
  Route,
  Rss,
  School,
  Search,
  Share2,
  ShieldCheck,
  Smile,
  SortAsc,
  SquarePen,
  Stethoscope,
  Timer,
  Trees,
  TriangleAlert,
  Umbrella,
  UserCheck,
  UserRoundSearch,
  Users,
  Vote,
  WalletCards,
  Wheat,
  Zap,
  type LucideIcon as LucideIconComponent
} from "lucide-react";

import { cn } from "@/lib/utils/cn";

type LucideIconProps = {
  name: string;
  className?: string;
  style?: CSSProperties;
  "aria-hidden"?: boolean;
};

const iconMap: Record<string, LucideIconComponent> = {
  accessible: Accessibility,
  account_balance: Landmark,
  account_balance_wallet: WalletCards,
  add: Plus,
  agriculture: Wheat,
  app_registration: SquarePen,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  badge: Badge,
  bolt: Zap,
  calendar_today: CalendarDays,
  check: Check,
  check_circle: CircleCheckBig,
  checklist: ListChecks,
  chevron_right: ChevronRight,
  circle: Circle,
  cloud_queue: Cloudy,
  compare_arrows: ArrowLeftRight,
  description: FileText,
  directions: Route,
  directions_bus: BusFront,
  directions_walk: Footprints,
  download: Download,
  eco: Leaf,
  edit_note: NotebookPen,
  expand_more: ChevronDown,
  factory: Factory,
  family_restroom: Users,
  filter_list: ListFilter,
  gavel: Gavel,
  groups: Users,
  help: CircleQuestionMark,
  home: Home,
  how_to_reg: UserCheck,
  how_to_vote: Vote,
  info: Info,
  landscape: Trees,
  location_city: Building2,
  location_on: MapPin,
  map: Map,
  medical_services: Stethoscope,
  menu_book: BookOpen,
  monitoring: ChartNoAxesColumnIncreasing,
  my_location: LocateFixed,
  payments: BadgeIndianRupee,
  pending: CircleEllipsis,
  person_search: UserRoundSearch,
  pets: PawPrint,
  pin_drop: MapPinned,
  policy: ShieldCheck,
  public: Globe,
  query_stats: ChartNoAxesColumnIncreasing,
  rss_feed: Rss,
  schedule: Clock,
  schema: Network,
  school: School,
  search: Search,
  sentiment_satisfied: Smile,
  share: Share2,
  share_location: MapPinPlus,
  sort: SortAsc,
  temple_hindu: Landmark,
  timer: Timer,
  touch_app: MousePointerClick,
  umbrella: Umbrella,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  warning: TriangleAlert,
  water_drop: Droplet,
  work: BriefcaseBusiness
};

export function LucideIcon({
  name,
  className,
  style,
  "aria-hidden": ariaHidden = true
}: LucideIconProps) {
  const Icon = iconMap[name] ?? CircleQuestionMark;

  return (
    <Icon
      aria-hidden={ariaHidden}
      className={cn("inline-block shrink-0 align-[-0.125em] text-[1.25rem]", className)}
      size="1em"
      style={style}
    />
  );
}
